name: Build and Push Docker Image

on:
  push:
    branches:
      - main  # This triggers only when code is pushed to the main branch, typically after a PR merge.

jobs:
  build_and_push:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Log in to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      - name: Build and Push Docker Image
        uses: docker/build-push-action@v4
        with:
          context: .  # Set to the Dockerfile directory if not at root
          push: true  # Push the image to the registry
          tags: ${{ secrets.DOCKER_USERNAME }}/goths-as-a-service-image:latest  # Replace with your Docker Hub username and desired image name
