name: Lint and Format Check

on:
  pull_request:
    branches:
      - main
      - "**"

jobs:
  lint_and_format:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: "18"

      - name: Install dependencies
        run: npm install

      - name: Run ESLint
        run: npm run lint
        continue-on-error: true

      - name: Run Prettier Check
        run: npx prettier --check .
        continue-on-error: true # Continue even if Prettier check fails

      - name: Add PR Comment if Lint or Format Check Fails
        if: failure() # Run if any step above failed
        uses: marocchino/sticky-pull-request-comment@v2
        with:
          message: |
            🚫 **Linting or Formatting Check Failed**
            Your pull request has issues with either linting or code formatting.
            - Run `npm run lint` to fix linting issues.
            - Run `npm run format` to apply Prettier formatting.

      # Explicitly fail the job if any of the checks failed
      - name: Fail on Lint or Format Errors
        if: failure()
        run: exit 1
